#!/bin/bash

# sysreport.sh
# Purpose: Display a concise system information report for this Linux computer.
# The script gathers system, hardware, network, and status data dynamically.
# Output is formatted using a heredoc template so it is easy to read.

#Basic identity information for the report heading.
current_user=$(whoami 2>/dev/null)
computer_name=$(hostname 2>/dev/null)
date_time=$(date '+%Y-%m-%d %H:%M:%S %Z' 2>/dev/null)

#Get operating system name and version from /etc/os-release.
os_name=$(source /etc/os-release 2>/dev/null && echo "$PRETTY_NAME")
[ -z "$os_name" ] && os_name="Unknown"

#Get system uptime in a short human-readable format.
uptime_info=$(uptime -p 2>/dev/null)
[ -z "$uptime_info" ] && uptime_info="Unknown"

#Get CPU model and remove extra spacing from the command output.
cpu_info=$(lscpu 2>/dev/null | grep "Model name" | cut -d: -f2 | sed 's/^[ \t]*//')
[ -z "$cpu_info" ] && cpu_info="Unknown"

#Get installed RAM from the Mem line of free output.
ram_info=$(free -h 2>/dev/null | awk '/^Mem:/ {print $2}')
[ -z "$ram_info" ] && ram_info="Unknown"

#List installed physical disks with vendor, model, and size.
disk_info=$(lsblk -dno VENDOR,MODEL,SIZE,TYPE |
    grep ' disk$' |
    sed 's/ disk$//' |
    paste -sd ',' - |
    sed 's/,/, /g')

[ -z "$disk_info" ] && disk_info="Unknown"

#Get video card product name from lshw. Fallback to lspci if lshw is unavailable.
video_info=$(lspci 2>/dev/null |
    grep -Ei 'vga|3d|display' |
    head -1 |
    cut -d: -f3- |
    sed 's/^ *//')

[ -z "$video_info" ] && video_info="Unknown"

#Find the network interface used by the default route.
default_interface=$(ip r 2>/dev/null | awk '/^default/ {print $5; exit}')

#Get the IPv4 address assigned to the default route interface.
host_address=$(ip a show "$default_interface" 2>/dev/null |
    awk '/inet / {print $2; exit}' |
    cut -d/ -f1)

[ -z "$host_address" ] && host_address="Unknown"

#Get default gateway IP address.
gateway_ip=$(ip r 2>/dev/null | awk '/^default/ {print $3; exit}')
[ -z "$gateway_ip" ] && gateway_ip="Unknown"

#Get DNS server for the default network interface, with resolv.conf as fallback.
dns_server=$(resolvectl dns "$default_interface" 2>/dev/null |
    head -1 |
    cut -d: -f2 |
    awk '{print $1}')

[ -z "$dns_server" ] && dns_server=$(grep '^nameserver' /etc/resolv.conf | head -1 | awk '{print $2}')
[ -z "$dns_server" ] && dns_server="Unknown"

#List logged-in users once each, separated by commas.
users_logged_in=$(who |
    awk '{print $1}' |
    sort -u |
    paste -sd, -)

[ -z "$users_logged_in" ] && users_logged_in="None"

#Show free space for local filesystems only, formatted as /mountpoint N.
disk_free=$(df -h -l -x tmpfs -x devtmpfs -x squashfs -x iso9660 --output=target,avail 2>/dev/null |
    awk 'NR>1 {
        printf "%s%s %s", sep, $1, $2
        sep=", "
    } END {print ""}')

S[ -z "$disk_free" ] && disk_free="Unknown"

#Count running processes.
process_count=$(ps -e --no-headers 2>/dev/null | wc -l)
[ -z "$process_count" ] && process_count="Unknown"

#Read 1, 5, and 15 minute load averages.
load_averages=$(awk '{print $1 ", " $2 ", " $3}' /proc/loadavg 2>/dev/null)
[ -z "$load_averages" ] && load_averages="Unknown"

#Extract listening TCP/UDP port numbers, remove duplicates, sort, and format with commas.
listening_ports=$(ss -tulnH |
    awk '{print $5}' |
    awk -F: '{print $NF}' |
    sort -n -u |
    paste -sd, -)

[ -z "$listening_ports" ] && listening_ports="None"

#Get firewall status while hiding error output.
ufw_status=$(grep '^ENABLED=' /etc/ufw/ufw.conf 2>/dev/null | cut -d= -f2)

[ "$ufw_status" = "yes" ] && ufw_status="active"
[ "$ufw_status" = "no" ] && ufw_status="inactive"
[ -z "$ufw_status" ] && ufw_status="Unknown"

cat <<EOF

System Report for $computer_name generated by $current_user, on $date_time

System Information
------------------
OS: $os_name
Uptime: $uptime_info
CPU: $cpu_info
RAM: $ram_info
Disk(s): $disk_info
Video: $video_info
Host Address: $host_address
Gateway IP: $gateway_ip
DNS Server: $dns_server

System Status
-------------
Users Logged In: $users_logged_in
Disk Space: $disk_free
Process Count: $process_count
Load Averages: $load_averages
Listening Network Ports: $listening_ports
UFW Status: $ufw_status

EOF
